---
title: "Graphing"
author: "Mira Flynn, Hazel Smith"
output: 
  github_document:
    toc: true
---
```{r}
library(tidyverse)
library(viridis)
```

```{r include=FALSE}
theme_common <- function() {
  theme_minimal() %+replace%
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(margin = margin(4, 4, 4, 4), size = 16),
    axis.title.y = element_text(margin = margin(4, 4, 4, 4), size = 16, angle = 90),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 12),
    strip.text.x = element_text(size = 12),
    strip.text.y = element_text(size = 12),
    panel.grid.major = element_line(color = "grey90"),
    panel.grid.minor = element_line(color = "grey90"),
    aspect.ratio = 10/16,
    plot.margin = unit(c(t = +0, b = +0, r = +0, l = +0), "cm"),
    plot.title = element_text(size = 18),
    # plot.title.position = "plot",
    plot.subtitle = element_text(size = 16),
    plot.caption = element_text(size = 12)
  )
}
```

## Original Paper Replication

```{r load-data}
df_ultimatum <- read.csv("data/data.csv")
```

```{r}
df_ultimatum_means <- df_ultimatum %>%
  group_by(idx, n, r, w, nPerRound, num_steps) %>%
  # summarize(
  #   mean_p = mean(mean_p)/((max(nPerRound))-1),
  #   mean_q = mean(mean_q)
  # )
  summarize(
    mean_p = mean(mean_p),
    mean_q = mean(mean_q)
  )
```

```{r original-replication-graph}
df_ultimatum_means %>%
  filter(nPerRound == 2, num_steps == 100000) %>%
  ggplot() +
  geom_line(aes(x = w, y = mean_p, color = "mean_p"), size = 1) +
  geom_line(aes(x = w, y = mean_q, color = "mean_q"), size = 1) +
  geom_point(aes(x = w, y = mean_p, color = "mean_p"), size = 2) +
  geom_point(aes(x = w, y = mean_q, color = "mean_q"), size = 2) +
  theme_common() + 
  labs(
    title = "2 players per round",
    y = "p, q"
  )
```

```{r original-time-graph}
df_ultimatum %>%
  filter(nPerRound == 2, num_steps == 100000) %>%
  group_by(idx, n, r, w, nPerRound, num_steps) %>%
  ggplot() +
  geom_line(aes(x = generation, y = mean_p, color = "mean_p")) +
  geom_line(aes(x = generation, y = mean_q, color = "mean_q")) +
  facet_wrap(~w) +
  # geom_point(aes(x = w, y = mean_p, color = "mean_p"), size = 2) +
  # geom_point(aes(x = w, y = mean_q, color = "mean_q"), size = 2) +
  theme_common()+
  # scale_x_continuous(labels = function(x) format(x, scientific = TRUE)) +
  theme(
    axis.text.x = element_text(angle=90)
  ) +
  labs(
    title = "2 players per round",
    y = "p, q"
  )


```

```{r extension-graph}
df_ultimatum_means %>%
  filter(num_steps == 100000) %>%
  ggplot() +
  geom_line(aes(x = w, y = mean_p, color = "mean_p"), size = 1) +
  geom_line(aes(x = w, y = mean_q, color = "mean_q"), size = 1) +
  geom_point(aes(x = w, y = mean_p, color = "mean_p"), size = 2) +
  geom_point(aes(x = w, y = mean_q, color = "mean_q"), size = 2) +
  facet_wrap(~ nPerRound) +
  theme_common() +
  labs(
    title = "2, 3, and 5 players per round",
    y = "p, q"
  )


```

```{r}
df_ultimatum %>%
  filter(nPerRound == 3, num_steps == 100000) %>%
  group_by(idx, n, r, w, nPerRound, num_steps) %>%
  # mutate(
  #   mean_p = mean(mean_p),
  #   mean_q = mean(mean_q)
  # ) #%>%
  mutate(
    mean_p = mean_p/(nPerRound-1)
    # mean_q = mean_q*(nPerRound-1)
  ) %>%
  ggplot() +
  geom_line(aes(x = generation, y = mean_p, color = "mean_p")) +
  geom_line(aes(x = generation, y = mean_q, color = "mean_q")) +
  facet_wrap(~w) +
  # geom_point(aes(x = w, y = mean_p, color = "mean_p"), size = 2) +
  # geom_point(aes(x = w, y = mean_q, color = "mean_q"), size = 2) +
  theme_common()+
  # scale_x_continuous(labels = function(x) format(x, scientific = TRUE)) +
  theme(
    axis.text.x = element_text(angle=90)
  ) +
  labs(
    title = "3 players per round",
    y = "p, q"
  )


```

```{r}
df_ultimatum %>%
  filter(nPerRound == 5, num_steps == 100000) %>%
  group_by(idx, n, r, w, nPerRound, num_steps) %>%
  # mutate(
  #   mean_p = mean(mean_p),
  #   mean_q = mean(mean_q)
  # ) #%>%
  mutate(
    mean_p = mean_p/(nPerRound-1)
    # mean_q = mean_q*(nPerRound-1)
  ) %>%
  ggplot() +
  geom_line(aes(x = generation, y = mean_p, color = "mean_p")) +
  geom_line(aes(x = generation, y = mean_q, color = "mean_q")) +
  facet_wrap(~w) +
  # geom_point(aes(x = w, y = mean_p, color = "mean_p"), size = 2) +
  # geom_point(aes(x = w, y = mean_q, color = "mean_q"), size = 2) +
  theme_common()+
  # scale_x_continuous(labels = function(x) format(x, scientific = TRUE)) +
  theme(
    axis.text.x = element_text(angle=90)
  ) +
  labs(
    title = "5 players per round",
    y = "p, q"
  )


```